export * from "./header";
export * from "./footer";
export * from "./ikeaProduct";
export * from "./wordInput";
export * from "./wordDisplay";
export * from "./modeCard";
export * from "./game";
export * from "./gameOver";
export * from "./coffeeButton";
